# SPDX-FileCopyrightText: 2021-2022 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "okh-tool"
version = "0.4.0"
edition = "2021"
publish = false

[features]
# Activate this to enable all OKH v1 properties, as per default, only those requried for converting to OKH LOSH are enabled
v1_non_losh = [] # feature has no explicit dependencies

[dependencies]
chrono = "0.4"
clap = { version = "4.0", features = ["cargo"] }
codify = { git = "https://github.com/hoijui/codify-rs.git" }
const_format = "0.2"
csv = "1.1"
git-version = "0.3"
git2 = { version = "0.15", default-features = false } # "default-features = false" is required for MUSL compatibility, to get rid of OpenSSL
globset = "0.4"
jsonschema = "0.16"
lingua = "1.3"
log = "0.4"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.9"
openssl-sys = { features = [ "vendored" ] } # better MUSL compatibility
projvar = { version = "0.16", git = "https://github.com/hoijui/projvar.git" }
regex = "1.5"
relative-path = { version = "1.6", features = ["serde"] }
reqwest = { version = "0", features = ["blocking"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
simplelog = "0.12"
spdx = "0.10"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
toml = "0.5"
url = { version = "2.2", features = ["serde"] }
walkdir = "2"
yaml-rust = "0.4"

[build-dependencies]
codify = { git = "https://github.com/hoijui/codify-rs.git" }
csv = "1.1"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
